steps:
  # ============================================================
  # PASO 1: Construir la imagen usando Docker nativo
  # ============================================================
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/sicoes-processor:latest', 
      '.'
    ]

  # ============================================================
  # PASO 2: Subir la imagen al Container Registry (GCR)
  # ============================================================
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sicoes-processor:latest']

  # ============================================================
  # PASO 3: Desplegar esa imagen en Cloud Functions
  # ============================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'sicoes-processor'
      - '--gen2'
      - '--region=us-central1'
      # Referencia a la imagen que acabamos de subir
      - '--image=gcr.io/$PROJECT_ID/sicoes-processor:latest'
      # Configuraciones de runtime
      - '--memory=512Mi'
      - '--concurrency=1'
      - '--max-instances=50'
      - '--timeout=300s'
      # Triggers
      - '--trigger-event-filters=type=google.cloud.storage.object.v1.finalized'
      - '--trigger-event-filters=bucket=TU_NOMBRE_DE_BUCKET' # <--- REEMPLAZA ESTO

images:
  - 'gcr.io/$PROJECT_ID/sicoes-processor:latest'

options:
  logging: CLOUD_LOGGING_ONLY